/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui.internal.LwMessageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LwMessageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LwMessageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LwMessageActivator.getInstance().getInjector(LwMessageActivator.ORG_ECLIPSE_PAPYRUS_UML_DIAGRAM_LIGHTWEIGHTSEQUENCE_MESSAGE_XTEXT_LWMESSAGE);
	}
	
}
