/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui;

import java.util.Collection;

import org.antlr.runtime.RecognitionException;
import org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.MessageRule;
import org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui.contentassist.antlr.LwMessageParser;
import org.eclipse.papyrus.uml.diagram.sequence.runtime.internal.providers.SequenceDiagramVisualIDQuarantine;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LwMessageUiModule extends
		org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui.AbstractLwMessageUiModule {
	private final MessageRule rule;

	public LwMessageUiModule(AbstractUIPlugin plugin) {
		this(plugin, MessageRule.DEFAULT);
	}

	public LwMessageUiModule(AbstractUIPlugin plugin, MessageRule rule) {
		super(plugin);

		this.rule = rule;
	}

	@Override
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		switch (rule) {
		case REQUEST:
			return RequestMessageContentAssistParser.class;
		case REPLY:
			return ReplyMessageContentAssistParser.class;
		default:
			return super.bindIContentAssistParser();
		}
	}

	public Class<? extends SequenceDiagramVisualIDQuarantine> bindSequenceDiagramVisualIDQuarantine() {
		return SequenceDiagramVisualIDQuarantine.Compatibility.class;
	}

	//
	// Nested types
	//

	private static class RequestMessageContentAssistParser extends LwMessageParser {

		@Override
		protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
			try {
				org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui.contentassist.antlr.internal.InternalLwMessageParser typedParser = (org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui.contentassist.antlr.internal.InternalLwMessageParser) parser;
				typedParser.entryRuleAbstractRequestMessage();
				return typedParser.getFollowElements();
			} catch (RecognitionException ex) {
				throw new RuntimeException(ex);
			}
		}

	}

	private static class ReplyMessageContentAssistParser extends LwMessageParser {

		@Override
		protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
			try {
				org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui.contentassist.antlr.internal.InternalLwMessageParser typedParser = (org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext.ui.contentassist.antlr.internal.InternalLwMessageParser) parser;
				typedParser.entryRuleReplyMessage();
				return typedParser.getFollowElements();
			} catch (RecognitionException ex) {
				throw new RuntimeException(ex);
			}
		}

	}
}
