/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.diagram.lightweightsequence.message.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LwMessageStandaloneSetup extends LwMessageStandaloneSetupGenerated{

	public static void doSetup() {
		new LwMessageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

