<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="j2eeprofile" nsURI="http://www.eclipse.org/emf/facade/2017/profile/test/j2ee"
    nsPrefix="j2eeprofile">
  <eClassifiers xsi:type="ecore:EClass" name="Bean">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Bean"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//BeanKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BeanKind">
    <eLiterals name="session"/>
    <eLiterals name="entity" value="1"/>
    <eLiterals name="messagedriven" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HomeInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Interface" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Interface">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_HomeInterface"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Finder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Interface" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Interface">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Finder"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
