<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="interaction" nsURI="http://www.eclipse.org/papyrus/2018/uml/interaction/logical"
    nsPrefix="seqd">
  <eClassifiers xsi:type="ecore:EClass" name="MElement" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
    </eTypeParameters>
    <eOperations name="getOwner">
      <eGenericType eClassifier="#//MElement">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eOperations name="getDiagramView" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments>
          <eUpperBound eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="verticalDistance" lowerBound="1" eType="#//OptionalInt">
      <eParameters name="other" lowerBound="1">
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="following" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MElement">
          <eTypeArguments>
            <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
          </eTypeArguments>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="nudge" lowerBound="1" eType="#//Command">
      <eParameters name="deltaY" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="remove" lowerBound="1" eType="#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" lowerBound="1"
        eType="#//MInteraction" changeable="false" volatile="true" transient="true"
        derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false">
      <eGenericType eTypeParameter="#//MElement/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" lowerBound="1" eType="#//OptionalInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottom" lowerBound="1"
        eType="#//OptionalInt" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MInteraction">
    <eOperations name="getDiagramView" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.gmf.runtime.notation/model/notation.ecore#//Diagram"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getElement" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MElement">
          <eTypeArguments>
            <eUpperBound eTypeParameter="#//MInteraction/getElement/E"/>
          </eTypeArguments>
        </eTypeArguments>
      </eGenericType>
      <eTypeParameters name="E">
        <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
      </eTypeParameters>
      <eParameters name="element" lowerBound="1">
        <eGenericType eTypeParameter="#//MInteraction/getElement/E"/>
      </eParameters>
    </eOperations>
    <eOperations name="getLifeline" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MLifeline"/>
      </eGenericType>
      <eParameters name="lifeline" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Lifeline"/>
    </eOperations>
    <eOperations name="getMessage" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MMessage"/>
      </eGenericType>
      <eParameters name="message" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    </eOperations>
    <eOperations name="addLifeline" lowerBound="1">
      <eGenericType eClassifier="#//CreationCommand">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Lifeline"/>
      </eGenericType>
      <eParameters name="xPosition" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Horizontal offset of the new lifeline from the left edge of the interaction frame."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="height" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Height of the lifeline shape to create, or {@code -1} for the default."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="getLifelineAt" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Queries the existing lifeline, if any, at or nearest to the left of a given x offset in the interaction."/>
      </eAnnotations>
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MLifeline"/>
      </eGenericType>
      <eParameters name="offset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="an x offset in the lifeline that is contained by or nearest to the right of the lifeline to be retrieved"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="getBottommostElement" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the bottommost element, such as a message end, contained by this interaction."/>
      </eAnnotations>
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments>
          <eUpperBound eClassifier="#//MElement">
            <eTypeArguments>
              <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
            </eTypeArguments>
          </eUpperBound>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifelines" upperBound="-1"
        eType="#//MLifeline" changeable="false" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//MMessage" changeable="false" containment="true" resolveProxies="false"/>
    <eGenericSuperTypes eClassifier="#//MElement">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interaction"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLifeline">
    <eOperations name="getOwner" eType="#//MInteraction"/>
    <eOperations name="getDiagramView" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.gmf.runtime.notation/model/notation.ecore#//Shape"/>
      </eGenericType>
    </eOperations>
    <eOperations name="following" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MElement">
          <eTypeArguments>
            <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
          </eTypeArguments>
        </eTypeArguments>
      </eGenericType>
      <eParameters name="element" lowerBound="1">
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments>
            <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="preceding" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MElement">
          <eTypeArguments>
            <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
          </eTypeArguments>
        </eTypeArguments>
      </eGenericType>
      <eParameters name="element" lowerBound="1">
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments>
            <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getExecutionOccurrence" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MExecutionOccurrence"/>
      </eGenericType>
      <eParameters name="occurrence" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExecutionOccurrenceSpecification"/>
    </eOperations>
    <eOperations name="getExecution" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MExecution"/>
      </eGenericType>
      <eParameters name="execution" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExecutionSpecification"/>
    </eOperations>
    <eOperations name="getDestruction" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MDestruction"/>
      </eGenericType>
      <eParameters name="destruction" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//DestructionOccurrenceSpecification"/>
    </eOperations>
    <eOperations name="insertExecutionAfter" lowerBound="1">
      <eGenericType eClassifier="#//CreationCommand">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExecutionSpecification"/>
      </eGenericType>
      <eParameters name="before" lowerBound="1">
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="offset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="height" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="specification" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
    </eOperations>
    <eOperations name="insertExecutionAfter" lowerBound="1">
      <eGenericType eClassifier="#//CreationCommand">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExecutionSpecification"/>
      </eGenericType>
      <eParameters name="before" lowerBound="1">
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="offset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="height" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="metaclass" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="insertMessageAfter" lowerBound="1">
      <eGenericType eClassifier="#//CreationCommand">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
      </eGenericType>
      <eParameters name="before" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The element after which to insert the message.  If it is an interaction fragment on this lifeline, then the new message’s send event is inserted after this element.  If it is a message, then the new message’s send event is inserted after the referenced message’s end that covers this lifeline."/>
        </eAnnotations>
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="offset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Vertical offset of the message from the element {@code before} it."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="receiver" lowerBound="1" eType="#//MLifeline">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The lifeline to receive the message.  May be the same as is sending it (this lifeline)."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="sort" lowerBound="1" eType="ecore:EEnum platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//MessageSort">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The sort of message to create."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="signature" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An optional message signature, either a signal or an operation."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="insertMessageAfter" lowerBound="1">
      <eGenericType eClassifier="#//CreationCommand">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
      </eGenericType>
      <eParameters name="beforeSend" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The element after which to insert the message send event.  If it is an interaction fragment on this lifeline, then the new message’s send event is inserted after this element.  If it is a message, then the new message’s send event is inserted after the referenced message’s end that covers this lifeline."/>
        </eAnnotations>
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="sendOffset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Vertical offset of the send event from the element before it, or from the lifeline head if none."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="receiver" lowerBound="1" eType="#//MLifeline">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The lifeline to receive the message.  May be the same as is sending it (this lifeline)."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="beforeRecv" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The element after which to insert the message receive event.  If it is an interaction fragment on the {@code receiver}, then the new message’s receive event is inserted after this element.  If it is a message, then the new message’s receive event is inserted after the referenced message’s end that covers this lifeline."/>
        </eAnnotations>
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="recvOffset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Vertical offset of the receive end from the element before it, or from the lifeline head if none."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="sort" lowerBound="1" eType="ecore:EEnum platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//MessageSort">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The sort of message to create."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="signature" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An optional message signature, either a signal or an operation."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="insertMessageAfter" lowerBound="1">
      <eGenericType eClassifier="#//CreationCommand">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
      </eGenericType>
      <eParameters name="beforeSend" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The element after which to insert the message send event.  If it is an interaction fragment on this lifeline, then the new message’s send event is inserted after this element.  If it is a message, then the new message’s send event is inserted after the referenced message’s end that covers this lifeline."/>
        </eAnnotations>
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="sendOffset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Vertical offset of the send event from the element before it, or from the lifeline head if none."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="receiver" lowerBound="1" eType="#//MLifeline">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The lifeline to receive the message.  May be the same as is sending it (this lifeline)."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="beforeRecv" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The element after which to insert the message receive event.  If it is an interaction fragment on the {@code receiver}, then the new message’s receive event is inserted after this element.  If it is a message, then the new message’s receive event is inserted after the referenced message’s end that covers this lifeline."/>
        </eAnnotations>
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="recvOffset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Vertical offset of the receive end from the element before it, or from the lifeline head if none."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="sort" lowerBound="1" eType="ecore:EEnum platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//MessageSort">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The sort of message to create."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="signature" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An optional message signature, either a signal or an operation."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="executionCreationConfig" eType="#//ExecutionCreationConfig">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The configuration specifying details about the creation of an execution associated for the message."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="insertMessageAfter" lowerBound="1">
      <eGenericType eClassifier="#//CreationCommand">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
      </eGenericType>
      <eParameters name="before" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The element after which to insert the message.  If it is an interaction fragment on this lifeline, then the new message’s send event is inserted after this element.  If it is a message, then the new message’s send event is inserted after the referenced message’s end that covers this lifeline."/>
        </eAnnotations>
        <eGenericType eClassifier="#//MElement">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="offset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Vertical offset of the message from the element {@code before} it."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="receiver" lowerBound="1" eType="#//MLifeline">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The lifeline to receive the message.  May be the same as is sending it (this lifeline)."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="sort" lowerBound="1" eType="ecore:EEnum platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//MessageSort">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The sort of message to create."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="signature" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An optional message signature, either a signal or an operation."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="executionCreationConfig" eType="#//ExecutionCreationConfig">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The configuration specifying details about the creation of an execution associated for the message."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="elementAt" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Query the element covering this lifeline that is at, or the nearest element before, a given y-coördinate {@code offset}."/>
      </eAnnotations>
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MElement">
          <eTypeArguments>
            <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
          </eTypeArguments>
        </eTypeArguments>
      </eGenericType>
      <eParameters name="offset" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="an offset in the y axis on the lifeline body (stem). Should be non-negative"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="nudgeHorizontally" lowerBound="1" eType="#//Command">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nudge the lifeline horizontally, along with all of the layout that depends on it."/>
      </eAnnotations>
      <eParameters name="deltaX" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="the distance by which to nudge the lifeline in the X axis (negative values nudging to the left, of course)"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionOccurrences" upperBound="-1"
        eType="#//MExecutionOccurrence" changeable="false" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executions" upperBound="-1"
        eType="#//MExecution" changeable="false" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destruction" eType="#//MDestruction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" lowerBound="1" eType="#//OptionalInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" lowerBound="1" eType="#//OptionalInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eGenericSuperTypes eClassifier="#//MElement">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Lifeline"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MExecution">
    <eOperations name="getOwner" eType="#//MLifeline"/>
    <eOperations name="getDiagramView" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.gmf.runtime.notation/model/notation.ecore#//Shape"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1" changeable="false"
        volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MOccurrence">
          <eTypeArguments/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finish" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MOccurrence">
          <eTypeArguments/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//MElement">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExecutionSpecification"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOccurrence" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="covered" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MLifeline"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startedExecution" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MExecution"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishedExecution" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MExecution"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//MElement">
      <eTypeArguments eTypeParameter="#//MOccurrence/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MExecutionOccurrence">
    <eOperations name="getOwner" eType="#//MLifeline"/>
    <eOperations name="getDiagramView" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.gmf.runtime.notation/model/notation.ecore#//IdentityAnchor"/>
      </eGenericType>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//MOccurrence">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExecutionOccurrenceSpecification"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMessageEnd">
    <eOperations name="getOwner" eType="#//MMessage"/>
    <eOperations name="getDiagramView" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.gmf.runtime.notation/model/notation.ecore#//IdentityAnchor"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="send" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="otherEnd" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MMessageEnd"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//MOccurrence">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//MessageEnd"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMessage">
    <eOperations name="getOwner" eType="#//MInteraction"/>
    <eOperations name="getDiagramView" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.gmf.runtime.notation/model/notation.ecore#//Connector"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getEnd" lowerBound="1">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MMessageEnd"/>
      </eGenericType>
      <eParameters name="end" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//MessageEnd"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendEnd" eType="#//MMessageEnd"
        containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedGetVisibility" value="true"/>
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveEnd" eType="#//MMessageEnd"
        containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedGetVisibility" value="true"/>
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="send" lowerBound="1" changeable="false"
        volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MMessageEnd"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receive" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MMessageEnd"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sender" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MLifeline"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiver" lowerBound="1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Optional">
        <eTypeArguments eClassifier="#//MLifeline"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//MElement">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Optional" instanceClassName="java.util.Optional"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OptionalInt" instanceClassName="java.util.OptionalInt"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Command" instanceClassName="org.eclipse.emf.common.command.Command"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CreationCommand" instanceClassName="org.eclipse.papyrus.uml.interaction.model.CreationCommand"
      serializable="false">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//EObject"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EObject" instanceClassName="org.eclipse.emf.ecore.EObject"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ExecutionCreationConfig" instanceClassName="org.eclipse.papyrus.uml.interaction.model.spi.ExecutionCreationConfig"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDestruction" eSuperTypes="#//MMessageEnd"/>
</ecore:EPackage>
